// Generated by CoffeeScript 1.6.3
var excuses, request, rex;

request = require('request');

rex = /<a.*?>(.*?)<\/a>/;

excuses = function(fn) {
  return request.get('http://developerexcuses.com/', function(err, res, body) {
    var match;
    if (err) {
      return fn('Oops, sth. is wrong');
    }
    match = rex.exec(body);
    excuses = match ? match[1] : 'No more excuses';
    return fn(null, excuses);
  });
};

module.exports = excuses;
